spring.application.name=auth

server.port=3000
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

microservice-demo.auth.jwt.secret=${JWT_SECRET:b3BWcmxJQkFIYmltTitQaEY3cm9zemN3ZXRkWFpBS28yVHoxZGRHRnJsRT0=}
microservice-demo.auth.jwt.expiration=900000
microservice-demo.auth.jwt.cookie-name=ACCESS_TOKEN
microservice-demo.auth.jwt.cookie-path=/api